openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "OnboardingApi"
servers:
  - url: "http://STD22073.com"
tags:
  - name: Etudiants
    description: Opérations liées aux étudiants
paths:
  /etudiants:
    get:
      summary: "Liste des étudiants"
      tags:
        - Etudiants
      responses:
        '200':
          description: "Une liste d'étudiants"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Student'
        '500':
          description: "Erreur du serveur"
    post:
      summary: "Ajouter un nouvel étudiant"
      tags:
        - Etudiants
      requestBody:
        description: "Etudiant à ajouter"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: "Etudiant ajouté avec succès"
        '500':
          description: "Erreur interne du serveur"
components:
  schemas:
    Student:
      type: "object"
      properties:
        id:
          type: "integer"
        nom:
          type: "string"
        datenaissance:
          type: "string"
